apiVersion: v1
kind: Service
metadata:
  name: router-service
  namespace: router
  labels:
    app: router-service
spec:
  selector: { app: router-service }
  ports:
    - name: http
      port: 80
      targetPort: 8080
