apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: inference-backend
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - inference-backend
  selector:
    matchLabels:
      app.kubernetes.io/name: inference-backend
  endpoints:
    - port: "9000"
      path: /metrics
      interval: 15s
