apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inference-backend.fullname" . }}-model
  labels:
    {{- include "inference-backend.labels" . | nindent 4 }}
data:
  {{ .Values.backend.model.configFileName }}: |
    model_id: {{ .Values.backend.model.id }}
    max_model_len: 4096
    dtype: float16
    gpu_memory_utilization: 0.85
