{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inference-backend.serviceAccountName" . }}
  labels:
    {{- include "inference-backend.labels" . | nindent 4 }}
{{- end -}}
