apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: router-ingress
  namespace: router
  annotations:
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - host: router.${ENV}.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: router-service
                port:
                  number: 9090
